### ISSUE TITLE
Change API to be based on add_XXX methods instead of providing lists

### ISSUE THREAD

**Issue by yoelk** [yoelk/instrumentino2#11]
currently the way to run is to instantiate an "Instrument" object and initialize it with the components and methods lists, Instead, I'd like to have "add_method" and "add_component" functions, similar to "add_widget". I think that's a better design (copying the kivy approach).

**Comment by snarfums** [comment]
It proably won't be used to define instruments, but also add remove_XXX for every add_XXX.  The remove_XXX methods would be used internally to remove the instrument objects when needing to load another instrument.
